### ISSUE TITLE
Can use with material-ui?

### ISSUE THREAD

**Issue by juanpastas** [carlosrocha/react-data-components#31]
How could I use react-data-components with a table like [this](http://www.material-ui.com/#/components/table).

![table material](http://goo.gl/gv89GS)

**Comment by carlosrocha** [comment]
That is currently not possible unless you modify all the components and change the classes. In the future I would like to make it easier to change, but I first need to get rid of the Twitter Bootstrap dependency.

**Comment by coljung** [comment]
Actually an easy way to implement this would be to have the ability to add custom classNames. I do not think this would conflict with having Twitter Bootstrap in the mean time.

I'm currently using react-toolbox ( based on material design as well ), which uses css-modules to manage styling, and i'm having a hard time customizing the look of my table because of the inability to customize css classes.  I am somehow able to do it, but in a very hacky way.

You have .container, .row, .table and these are very global and general. I see they are based of Bootstrap, but they make it very hard to use with anything other than Bootstrap.

Could we propose a Pull Request with the ability to add custom classes ?
