### ISSUE TITLE
Redux - Key data

### ISSUE THREAD

**Issue by brycejacobs** [carlosrocha/react-data-components#37]
Would you be open to accepting a PR that keys the data that's being loaded on the datatable? To better support having multiple tables rendered at once.

**Comment by carlosrocha** [comment]
How would that work? Yes, feel free to send a PR.

**Comment by popasquat89** [comment]
I was thinking it could work similar to how redux-form works. As of right now, we have a set of actions that are used in the selectable example, through wrapping a prop to dispatch function.

https://github.com/carlosrocha/react-data-components/blob/master/example/redux/containers/DataTable.js#L12-L23

I think the most logical way, and to avoid breaking anything, is to have it to where the actions accept a key property that can be used to push / pull from certain data.

So something like:

```
 onFilter(key, {target: {value}}) {
    dispatch(actions.dataFilter(key, value, filters, domain));
  }
```

Each action can have a default domain, so that if it's not specified the data component works the same.

**Comment by carlosrocha** [comment]
That sounds good, we would also need a way to namespace each table state in the store, probably initialized by the HOC like in redux-form, what do you think?

**Comment by brycejacobs** [comment]
@carlosrocha Thank you, much appreciated!

**Comment by carlosrocha** [comment]
Thanks for the PR!
